MythTV/packaging

- deb/debian/mythtv-frontend.logrotate
- deb/debian/mythtv-transcode-utils.logrotate
Fixes https://bugs.launchpad.net/mythbuntu/+bug/1402782
> Adding missingok to frontend and transcoding logrotate configs

- deb/debian/patches/default_theme.patch
This fixes our packaging of master which is currently failing to build do to upstream changes. (Fuzz not allowed)
> Actually fix the master default theme patch

- deb/debian/control
- deb/debian/control.in
- deb/debian/theme.stub
(which was dropped from Debian unstable) to fonts-dejavu (LP: #1882108)
> Update runtime dependencies on the transitional dummy ttf-dejavu

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
This PR should be matched to fixes/31 branch with just my updates.
> OSX: update to allow user to specify database version

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
Fix issue where compile fails due to conflicting ffmpeg libraries from macports in master
> OSX: fix linking issue when ffmpeg is installed by macports (master)

- OSX/build/macports_ansible/README.md
- OSX/build/macports_ansible/codesignAndPackage.zsh
- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
Updated the OSX build script to allow for correct application code signing and notarization.
> Master: OSX: Update macports/ansible build script to include code signing

- OSX/build/macports_ansible/README.md
- OSX/build/macports_ansible/codesignAndPackage.zsh
- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
Updated the OSX build script to allow for correct application code signing and notarization.
> Fixes/31: OSX: Update macports/ansible build script to include code signing

- deb/debian/mythfrontend.sh
@superm1 apply https://github.com/MythTV/packaging/pull/95 to fixes/31
> Prevent frontend from resurecting when the database is inaccessible

- deb/debian/mythfrontend.sh
@superm1 apply https://github.com/MythTV/packaging/pull/95 to fixes/30
> Prevent frontend from resurrecting when the database is inaccessible

- deb/debian/mythfrontend.sh
The mythfrontend.real process disables DPMS ie the screensaver while it plays a video, then normally restores the DPMS settings when video playback finishes.  But if mythfrontend.real crashes, the screensaver stays forever disabled.
This commit extends the existing functionality that loops to restart mythfrontend.real after a crash to also restore DPMS settings, so that the screensaver can continue to function normally
> Check for DPMS settings and restore them after mythfrontend.real crash

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
- added options for changing repo prefix and whether to generate apps
- rebasing @rpath dylibs for unbundled executables
> Enhanced script for non-bundled build for macOS

- OSX/build/macports_ansible/codesignAndPackage.zsh
- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
remove PYTHONHOME variable from startup script as it no longer is necessary (and breaks) python310
> master - OSX: Fix embedded python for python310

- OSX/build/macports_ansible/codesignAndPackage.zsh
- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
remove PYTHONHOME variable from startup script as it no longer is necessary (and breaks) python310
> Fixes/32 - OSX: Fix embedded python for python310

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
- Update defaults to reflect current state of macports (i.e. mysql8, python310)
- Add logic to set default databse install to mariadb-10.5 for older macOS versions as macports does not support mysql8 for Mojave and older
- Cleanup py2app and pyvenv logic to parve packages after gsed is installed
> OSX: (Master) Miscellaneous fixes updated and cleanup

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
- removed unnecssary 33 tag
- force running ansible on each run
- update default prefix to use HOME vs ~
- migrate to ansible based installation of python virtualenv
- cleanup unused PYTHON variables
- cleanup PY2APP requirements
> Fixes/32 OSX: Migrate python to ansible based python venv

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
- removed unnecssary 33 tag
- force running ansible on each run
- update default prefix to use HOME vs ~
- migrate to ansible based installation of python virtualenv
- cleanup unused PYTHON variables
- cleanup PY2APP requirements
> Master: OSX: Migrate python to ansible based python venv

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
> OSX: Master - update default python to 311

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
- Fix hard coded python 310 path
- Update help message to use values from default variables
- Add lib search for libhdhomeruns new isolated location
- correct install_name_tool call for updated input style
- misc comment fixes
> OSX: Fix python version bug and other misc

- deb/build-debs.sh
> Set privilege escalation command when already root

- macOS/compileMythtvAnsible.zsh
Fix macOS versioning in master
> macOS: Fix master version

- deb/debian/changelog
- deb/debian/changelog.in
Add new build for mythbuntu v35-pre.
> Update mythtv master to v35-Pre

- android/docker/Dockerfile
- android/docker/start.sh
- android/makelibs.sh
bring android docker configuration into sync with recommended versions from wiki and add required python3 
fix libbluray compile error by updateing to newer version (1.1.2 to 1.3.4)
> android docker configuration and build

- macOS/compileMythtvAnsible_cmake.zsh
Updates include:
- Update of help message for accuracy and notarization tip
- Add github specific logic to skip keychain unlock
- Update default qt to qt6 for macports and homebrew
- Fix notarization keychain input typo
- Remove unnecessary LDFLAGS
This should be applied only to master
> macOS: update cmake compile script

- macOS/compileMythtvAnsible.zsh
- macOS/compileMythtvAnsible_cmake.zsh
Update default version for new fixes/35 branch only.
> fixes/35: macOS: update for fixes/35 branch cut

- deb/debian/changelog
- deb/debian/changelog.in
MythTV created a new release branch fixes/35, see
http://lists.mythtv.org/pipermail/mythtv-dev/2025-February/079936.html
Refs #199
> Debian: Enable builds on fixes/35 branch

- deb/debian/control
- macOS/compileMythtvAnsible_cmake.zsh
Change font name from fonts-freefonts-ttf to fonts-freefont-ttf
> Fix name fonts-freefont-ttf
