MythTV/packaging

- deb/debian/mythtv-backend.init
- deb/debian/mythtv-common.postinst
+ Fix postinst to not require ubuntu-specific 'syslog' user.
+ Include sysvinit script suitable for wheezy and jessie (latter
case still needed especially on upgraded systems that may not
have switched to systemd init).
> Remaining fixes for source-package Debian compatibility.

- deb/debian/changelog.in
Would like this commited to fixes/0.27 at least. 
Causes version to come out correctly as e.g. 0.27.5+fixes.20150821.e2a11c9-manualbuild
Maybe this should (for now) go into master as well?
> Correct version for fixes/0.27 builds

- deb/debian/mythtv-database.postinst
- deb/debian/mythtv-database.preinst
Agreed with superm1 this should go into Master for now.
Later, after 0.28 users' update-testing, this *along with separate commit #62 should hopefully be backported to fixes/0.27 .
> Fixes to preinst/postinst to handle updating to ipv6-compatible mysql-socket without prompting user.

- deb/debian/mythtv-backend.init
Now fixed//tested, obviously only affects sysvinit (especially older but supported debian systems).
Push-requesting to Master and separately to fixes/0.27
> Correct sysvinit script, wait for backend to close, fixes race condition

- deb/debian/mythtv-database.cron.weekly
The mythtv backup scripts exists with error code 2 and does no backup if root has an .my.cnf file for mysqldump with different user.
The reason is already described in then code of "mythconverg_backup.pl":
verbose($verbose_level_debug,
'', "Attempting to use supplied password for $mysqldump.",
'Any [client] or [mysqldump] password specified in the MySQL'.
' options file will',
'take precedence.');
By reading the /etc/default/mythtv-backend file and using sudo if the mythv user is set,this could be solved.
> https://code.mythtv.org/trac/ticket/12964

- deb/debian/mythtv-common.install
- deb/debian/mythtv-common.links
- deb/debian/rules
The packaging/deb scripts create symlinks to Droid fonts that are no
longer available on Debian or Ubuntu. However, mythtv already has the
Droid fonts and installs them when mythtv is built from source.
This commit changes the debian/ubuntu packaging to install mythtv's
droid fonts instead of relying on fonts that were deprecated two years
ago and replaced by dejavu fonts that don't look right.
> Debian/Ubuntu: Install Droid fonts instead of symlinking.

- deb/debian/mythtv-setup.sh
This is due to RUNNING=$(status mythtv-backend | grep running) failing.
Replace with RUNNING=$(ps -A | grep mythbackend) which works on all systems.
Tested on Ubuntu 16.04 LTS and Debian Stretch
Edit 20180418
see https://code.mythtv.org/trac/ticket/13160
Also applies to Ubuntu 18.04
> mythtv-backend does not stop when running mythtv-setup.

- android/android-utilities/setenv.sh
android-sdk-linux is already part of $ANDROID_SDK_ROOT
Running setenv.sh without this change results in an error message:
```
ls: cannot access '/home/mythtv/android/android-sdk-linux/android-sdk-linux/build-tools': No such file or directory
Using discovered tools version 
```
and ANDROID_BUILD_TOOLS_REVISION is empty
> Fix path to build-tools in setenv.sh

- android/Readme.md
- android/android-utilities/setenv.sh
- android/docker/docker_init.sh
- android/installapk.sh
- android/pushapk.sh
- android/startgdbserver.sh
This removes the requirement to make additional symlinks.
> Make $HOME/Android the expected installation source of SDK and Studio

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
Fix issue where compile fails due to conflicting ffmpeg libraries from macports in fixes/v31
> OSX: fix linking issue when ffmpeg is installed by macports (fixes/31)

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
Update to latest OSX build script. This syncs with the script confirmed by third part to work on the mailing list.
> OSX: back out FFMPEG PKG Config path change (no longer necessary) - master

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
Update to latest OSX build script.  This syncs with the script confirmed by third part to work on the mailing list.
> OSX: back out FFMPEG PKG Config path change (no longer necessary) fixes/v31

- deb/debian/mythfrontend.sh
I am using MythTV version 31 installed on Xubunutu 21.04 or 20.04 via the mythbuntu ppa.
When I launch the frontend without the backend running, it displays the loading bar, but when I try to exit, either before or after it times out, it thinks the frontend has crashed, so it relaunches. This obviously creates an inescapable loop, which is annoying.
Killing mythfrontend via xfce4-taskmanager does break the loop, but oddly mythfrontend.real doesn't show up in xfce4-taskmanager while gnome-system-monitor shows both.
Adding exit code 130 to the list in the script breaks the loop.  Exit code 130 is GENERIC_EXIT_NO_MYTHCONTEXT (https://github.com/MythTV/mythtv/blob/master/mythtv/libs/libmythbase/exitcodes.h ), which is a result of exiting the GUI startup screen (see mythcontext.cpp …
> Prevent frontend from resurecting when the database is inaccessible

- deb/debian/source/options
Building using ./build-debs.sh master fails on mythtv master due
to the file .clazy which is classified as local change to the sources.
Note file .clazy does not exist in previous version e.g. fixes/31.
Fixes #100
> Ignore .clazy file when building from source

- deb-light/package.sh
Add libcec6 to dependencies so deb packages can be generated and installed on Raspberry Pi OS Bullseye.
> Add libcec6 to dependencies

- deb/debian/40-mythtv.conf
On modern rsyslog (per git, >= 7.3 or so, in 2012), the use of the '~'
action leads to a slew of deprecation warnings when rsyslog starts:
rsyslogd: warning: ~ action is deprecated, consider using the 'stop' statement instead [v8.2102.0 try https://www.rsyslog.com/e/2307 ]
Switch to the 'stop' directive, which is functionally equivalent.
> deb: stop using deprecated rsyslog '~' action

- OSX/build/macports_ansible/codesignAndPackage.zsh
- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
Updates to the macOS build script to include:
- Default to fixes/32 branch cut
- Migrate py2app call from deprecated ttvdb.py to ttvdb4.py
- Add the option to compile using QT6
Update the codesigning routine to use Xcode 13's new methods.
> Update OSX fixes/32  build script and codesiging

- deb/debian/mythtv.make
Fix building on Debian fails due to git:// URLs if user has not set up GitHub credentials #123 
I have verified that all the compilation works correctly in Debian 11 and 12
> Fix Error mythtv.make #123 Debian

- deb-light/config.sh
Hi
I use a 32-bit armhf docker container in a 64-bit aarch64 host to build mythtv-light for my Raspberry Pi.
The deb-light/config.sh script uses the host arch instead of the build arch at one point and so ffmpeg ends up getting configured wrongly and won't compile.
This pull request fixes it.
> Allow building armhf deb-light packages on aarch64 hosts

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
Update the OSX compile script to:
- factor in a request to change the file architecture tagging
- update the python embeds to use ttdvb4
- fix the call to ansible in alignment with the mythtv ansible changes
> OSX: Master - update for arch tagging, python libs, and ansible playbook changes

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
Update the OSX compile script to:
factor in a request to change the file architecture tagging
update the python embeds to use ttdvb4
fix the call to ansible in alignment with the mythtv ansible changes
> OSX: Fixes/32 - update for arch tagging, python libs, and ansible playbook changes

- OSX/build/macports_ansible/README.md
- OSX/build/macports_ansible/codesignAndPackage.zsh
- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
- Update README
- Codesign: Update code sign script to automatically unlock the keychain. 
- Compile Script: Update python and database defaults to track macports.
- Compile Script: Minor py2app cleanup to make python deployment work on the githu… 
- Compile Script: Add ability to specify the compiler used
> OSX: master - Update compile script, code signing, and Readme

- OSX/build/macports_ansible/README.md
- OSX/build/macports_ansible/codesignAndPackage.zsh
- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
- Update README
- Codesign: Update code sign script to automatically unlock the keychain. 
- Compile Script: Update python and database defaults to track macports.
- Compile Script: Minor py2app cleanup to make python deployment work on the githu… 
- Compile Script: Add ability to specify the compiler used
> OSX: Fixes/32 - Update compile script, code signing, and Readme

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
- Add missing mysqlclient dependency
- Move the pip install wheel and py2app into a separate call to pip to aide other python packages that require wheel and remove them from the py2app package list
> MASTER - OSX: ansible compile script - Fix missing mysqlclient dependency, move wheel and py2app to install first

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
- Add missing mysqlclient dependency
- Move the pip install wheel and py2app into a separate call to pip to aide other python packages that require wheel and remove them from the py2app package list
> FIXES/32: OSX: ansible compile script - Fix missing mysqlclient dependency, move wheel and py2app to install first

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
- Correct Fixes/32 version number 
- Update defaults to reflect current state of macports (i.e. mysql8, python310)
- Add logic to set default databse install to mariadb-10.5 for older macOS versions as macports does not support mysql8 for Mojave and older
- Cleanup py2app and pyvenv logic to parve packages after gsed is installed
> OSX: (Fixes/32) Miscellaneous fixes updated and cleanup

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
- Update default python to 311
- Update branch tagging to fixes/33
> OSX: Fixes/33 - Correct branch tag and update python to 311

- deb-light/config.sh
Fixes incorrect detection of arm64 as a 32-bit platform.
Adds default set of config options for arm64.
Cortex-a72 was chosen as the default because this used by the Raspberry Pi 4
Most of the options are just copied over, if something needs to be changed, let me know.
Fixes: #149
> Add default set of config options for arm64

- deb-light/package.sh
If the deb package already exists during packaging, then on `exec` the original arguments are lost, resulting in unexpected behavior.
Passing the arguments on `exec` keeps the behavior consistent.
I think it would be beneficial in `fixes/33` too. Is it going to be cherry-picked, or should I open a pr against `fixes/33`?
> deb-light: package.sh pass arguments on exec

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
Fixed some issues with compileMythfrontendAnsible.zsh found when compiling mythbackend:
- fixed bug in rebaseLibs() for handling blank strings
- fixed bugs calling ansible-playbook
- passing in ansible extra flags (so that we can specify database to use)
- command args were not being parsed properly due to different zsh behavior
- added version 33 into options as master mythtv version is now 34
> Fixed some issues with compileMythfrontendAnsible.zsh

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
Clean up the compile script attempting to correct for fortmatting issues.  Apply updates for latest qt6 build and ansible configuration. Finally, fix internal links of dylibs for mythutil and mythmetadatalookup.
- tidy up trailing whitespace
- update to consitstent variable nameing
- update qt6 logic
- update mythtv build flags for deprecated qtwebkit/qtscript
- fix dylib paths for mythutil, mythmetadatalookup
> MASTER - OSX: tidy and assorted fixes

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
Clean up the compile script attempting to correct for fortmatting       
issues.  Apply updates for latest qt6 build and ansible configuration.  
Finally, fix internal links of dylibs for mythutil and                  
mythmetadatalookup.                                                     
- tidy up trailing whitespace                                           
- update to consitstent variable nameing                                
- update qt6 logic                                                      
- update mythtv build flags for deprecated qtwebkit/qtscript            
- fix dylib paths for mythutil, mythmetadatalookup
> Fixes/33 - OSX: tidy and assorted fixes                                            

- OSX/build/macports_ansible/codesignAndPackage.zsh
- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
Using the shellscript linter, clean up compileMythfrontendAnsible.zsh and codesignAndPackage.zsh
- Delete generate_dmg flag
- Remove unnecessary variables
- Fix typos
- Apprpriately double quite variables
- Fix installLibs enabling recursive library re-linking
- Fix libmyth*.dylibs which were not being linked internally
> Master: OSX: code cleanup based on linter suggestions

- OSX/build/macports_ansible/codesignAndPackage.zsh
- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
Using the shellscript linter, clean up compileMythfrontendAnsible.zsh and codesignAndPackage.zsh
- Delete generate_dmg flag
- Remove unnecessary variables
- Fix typos
- Apprpriately double quite variables
- Fix installLibs enabling recursive library re-linking
- Fix libmyth*.dylibs which were not being linked internally
> Fixes/33: OSX: code cleanup based on linter suggestions

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
- MYSQL 8 now requires some system variables to help pip and pkg_config locate its support files
- Remove git pull of the mythtv packaging directory as the compile script no longer requires any of the support files.  This also assums that the user has cloned this directory on their own.
> Master OSX: Add new mysql flags and clone of packaging

- OSX/build/macports_ansible/compileMythfrontendAnsible.zsh
- MYSQL 8 now requires some system variables to help pip and pkg_config locate its support files
- Remove git pull of the mythtv packaging directory as the compile script no longer requires any of the support files.  This also assums that the user has cloned this directory on their own.
> Fex/33 OSX: Add new mysql flags and clone of packaging

- deb/debian/patches/bindings_install_paths.patch
Issue mythtv/#843 fixes a flaw in subseqent builds of the Python-Bindings. 
https://github.com/MythTV/mythtv/issues/843
Commit mythtv/bc973e3 solved this but needs an update to the patches provided by `packaging/debian`
https://github.com/MythTV/mythtv/commit/bc973e32104a8ffdb73275662ad9d1e5b358a89b
It concerns the file `mythtv/bindings/python/Makefile`.
Please review and merge.
> Debian: Sync patch bindings_install_paths.patch to MythTV master

- macOS/compileMythtvAnsible.zsh
Fix parsing for qt and mysql on homebrew now that they have changed
naming conventions upstream
> fixes/34 - macOS: cleanup for new homebrew qt mysql versioning

- macOS/compileMythtvAnsible.zsh
macOS: remove now obsolete -ld_classic flag  
- Remove the -ld_classic flag that was introduced as a workaround in Sonoma now that the issue has been resolved by Apple.
- Additionally fix the liberation font path as it changes location for macports installs.
Please cherry-pick onto fixes/34 as well
> macOS: remove now obsolete -ld_classic flag

- macOS/README.md
- macOS/compileMythtvAnsible.zsh
- macOS/compileMythtvAnsible_cmake.zsh
- Add new cmake based compile script
- Update to python312 on macports, 313 on homebrew 
Scripts will be updated to python313 once all the approrpiate packages are also added (ansible)
- Clean up and update README.md
> macOS: Add cmake based compile script, update macports to python312

- macOS/compileMythtvAnsible.zsh
Updates include:
- update macports default python to 313
- fix py2app packages
- diable egl by default
This should be applied to both master and fixes/34
> macOS: Update legacy compile script

- macOS/compileMythtvAnsible.zsh
Primary updates include
- spelling and lint based cleanup
- make python313 the default
- updates to correspond with ansible
> macOS: update compile script to align with master

- macOS/compileMythtvAnsible_cmake.zsh
With the new cmake process, application bundling is now moved into
the build process rendering the "skip-build" flag and legacy logic
non-functional.  Add the repackage-only flag to add back the removed
repackaging functionality via the cmake mechanism.
Additionally clean up to the github runner detection code.
Please apply to master only.
> macOS: replace skip-build flag with repackage-only flag (master only)

- deb/debian/changelog
- deb/debian/changelog.in
MythTV changed git master to v36-Pre, see
http://lists.mythtv.org/pipermail/mythtv-dev/2025-February/079936.html
Refs #199
> Ubuntu: Enable builds on MythTV master (v36-Pre)

- deb/debian/control
- deb/debian/rules
Ubuntu has dropped Qtwebkit5.
LinK: https://bugs.launchpad.net/ubuntu/+source/qtwebkit-opensource-src/+bug/2100639
> Stop compiling mythbrowser

- deb/debian/mythtv-common.config
- deb/debian/mythtv-common.postinst
Albeit 'pwgen' is marked as 'Pre-Depends' in the control file, it is missing during installation.
Use '/dev/urandom' to generate a password, instead.
Fixes: MythTV/packaging#206
> Debian: Workaround for missing 'pwgen' utility
